appium_url=http://localhost:4723/wd/hub
platformName=Android
# App package ID
appPackage=com.swaglabsmobileapp
# Leave empty to prevent auto-launch (required for launch_and_install)
appActivity=
deviceName=
capabilities=