# Staging Environment Configuration

# Application URLs
url: "https://staging.example.com"
api_url: "https://api-staging.example.com"

# Credentials
username: "staging_user"
password: "staging_password"

# API Configuration
api_timeout: 30
api_retry: 3

# Database Configuration
db_host: "staging-db.example.com"
db_port: 5432
db_name: "staging_db"

# Custom Configuration
custom_config:
  feature_flag_1: true
  feature_flag_2: false
  max_retry: 3
  debug_mode: false
